#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/cea7b1ca-8cab-4570-acae-6f0e009565de 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String shoppingList;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
int reading = 0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  pinMode(A1, INPUT);
  shoppingList = "";
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  reading = analogRead(A1);
  Serial.println(reading);
  if (reading > 150 && reading < 200) {
    shoppingList = shoppingList + "Beans | ";
  } else if  (reading > 230 && reading < 330) {
    shoppingList = shoppingList + "Soup | ";
  } else if  (reading > 400 && reading < 460) {
    shoppingList = shoppingList + "Gravy | ";
  } else if  (reading > 660 && reading < 720) {
    shoppingList = shoppingList + "Biscuits | ";
  } else if  (reading > 1000) {
    shoppingList = shoppingList + "Eggs | ";
  }
  delay(200);
}

void onShoppingListChange() {
  // Do something
}

