// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "cea7b1ca-8cab-4570-acae-6f0e009565de";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onShoppingListChange();

String shoppingList;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(shoppingList, READWRITE, ON_CHANGE, onShoppingListChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
